apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilist-be-dev
  namespace: dev
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: cilist-be-dev
  template:
    metadata:
      labels:
        app: cilist-be-dev
    spec:
      containers:
      - name: cilist-be-dev
        image: triagungtio/cilist-be:{{NEW_TAG}}
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: cilist-env-dev
        # readinessProbe:
        #     initialDelaySeconds: 1
        #     periodSeconds: 2
        #     timeoutSeconds: 1
        #     successThreshold: 1
        #     failureThreshold: 1
        #     httpGet:
        #       path: /health
        #       port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cilist-be-dev
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cilist-be-dev
