apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilist-be-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilist-be-prod
  template:
    metadata:
      labels:
        app: cilist-be-prod
    spec:
      containers:
      - name: cilist-be-prod
        image: triagungtio/cilist-be:{{NEW_TAG}}
        ports:
        - containerPort: 5000
        resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
        envFrom:
        - configMapRef:
            name: cilist-env-prod
        readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /health
              port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cilist-be-prod
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cilist-be-prod
