apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deployment-be-prod
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cilist-be-prod
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60